Module1 task3 Начинаем программировать
htmlacademy-react/832117-what-to-watch-5 pull request #5
Opened 2020-10-13 10:55 UTC by dermorgenstern

задание начинаем программировать. не смог победить svg в компоненте header, пока закомментировал.

2020-10-13 11:13 UTC, aelyseev commented
`начальный коммит 1-3`
не совсем верный заголовок коммита

2020-10-13 11:19 UTC, aelyseev requested changes

2020-10-13 11:19 UTC, aelyseev commented on src/components/app/app.js
> +    console.log(userName);
console

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-footer/main-footer.js
> +        <a className="logo__link logo__link--light">
нет href

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
ненужные комменты

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-header/main-header.js
> +          <a className="logo__link">
href

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-header/main-header.js
> +                {/* <img src="img/btn--play.svg" width="20" height="20" ></img> */}
нунужный коммент

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-header/main-header.js
> +                {/* <img src="img/btn--list.svg" width="20" height="20"></img> */}
и тут

2020-10-13 11:19 UTC, aelyseev commented on src/components/main-content/main-content.js
> +      <MainCatalog></MainCatalog>
**не ошибка**
`<MainCatalog></MainCatalog>` => `<MainCatalog />` и ниже

2020-10-13 11:50 UTC, aelyseev commented
Кстати, а что за проблема с svg в header ?

2020-10-13 12:37 UTC, dermorgenstern commented on src/components/app/app.js
> +    console.log(userName);
..упси
исправлю

2020-10-13 12:46 UTC, dermorgenstern commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
> Кстати, а что за проблема с svg в header ?

Раньше импорторовал svg и вставлял в img как src={importedSvg}. Но это был create-react-app. Сейчас делаю тоже смое - ругается webpack. Это же валидный способ использования или в create react app  что-то поднастроено?
Если вставляю инлайн то неотображается но размер кнопки увеличиваетя - тоесть как бы есть, но нет ;)

2020-10-13 12:51 UTC, dermorgenstern commented on src/components/main-footer/main-footer.js
> +        <a className="logo__link logo__link--light">
Я так понял что используем markup как шаблоны и не трогаем их, там линки все пустые - я не стал заостряться на разметке. PS и я не знаю что туда ставить - "#"?

2020-10-13 13:01 UTC, dermorgenstern commented on src/components/main-footer/main-footer.js
> +        <a className="logo__link logo__link--light">
Так а я же и не возражаю - исправим!

2020-10-13 13:03 UTC, aelyseev commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
У вас в webpack не хватает loader для такого типа файлов. Внутри `create-react-app` уже такой loader подключен.
Можно сделать вот так https://webpack.js.org/loaders/file-loader/, или вот так
https://webpack.js.org/loaders/url-loader/

Второй loader делает data-uri если файл меньше лимита. Можете сделать сейчас, или потом — скорее всего вам еще отдельно раскажут.

2020-10-13 13:03 UTC, aelyseev commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
замените правило в примерах, так чтобы `.svg` под них подпадало.

2020-10-13 13:09 UTC, dermorgenstern commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
Ага, я так и думал. Не хотел настройки трогать, но попробую - в жизни пригодиться. Спасибо!

2020-10-14 03:43 UTC, dermorgenstern commented
исправил ошибки

2020-10-14 06:44 UTC, aelyseev commented on src/components/app/app.js
> +      <MainHeader userName={userName}></MainHeader>
не ошибка, но
`<MainHeader userName={userName}></MainHeader>` => `<MainHeader userName={userName} />`

2020-10-14 06:46 UTC, aelyseev requested changes

2020-10-14 06:46 UTC, aelyseev commented on src/components/main-header/main-header.js
> +// import btnPlay from "./btn--list.svg";
комментарии так и остались

2020-10-14 11:09 UTC, dermorgenstern commented
Убрал комментарии, теперь работает с импортом

2020-10-14 11:14 UTC, aelyseev approved these changes

2020-10-14 11:14 UTC, merged