Задание 2. Маршрутизация (React Router)  7. Личный проект: маршрут по тайным тропам
htmlacademy-react/832117-what-to-watch-5 pull request #6
Opened 2020-10-21 03:27 UTC by dermorgenstern

Pull request для задания 2. Маршрутизация (React Router)  7. Личный проект: маршрут по тайным тропам
выгрузил в netlify https://what-to-whatch-task2.netlify.app/
сделать как в видео уроке перерисовку по изменении url не удалось - пытается грузить несуществующую страницу. на stack overflow говорят надо сервер настараивать чтобы выдавал одну и туже страницу.

2020-10-21 13:12 UTC, aelyseev commented on package.json
> -    "eslint-plugin-react": "^7.18.3",
ага, отлично — зевнул я в прошлый раз

2020-10-21 13:23 UTC, aelyseev requested changes

2020-10-21 13:23 UTC, aelyseev commented on src/components/aux-nav/aux-nav.js
> +  let style = {backgroundColor: `#866`};
лучше `const` вместо `let`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/AddReview.js
> +            <a href="main.html" className="logo__link">
раз у нас роутер, то `a` => `Link`

2020-10-21 13:23 UTC, aelyseev commented on src/components/aux-nav/aux-nav.js
> +      <Link to={`/`} > Main </Link>
не ошибка

приятно когда у ссылок есть `title`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/AddReview.js
> +                <a href="movie-page.html" className="breadcrumbs__link">The Grand Budapest Hotel</a>
тоже `Link`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/Film.js
> +            <a href="main.html" className="logo__link">
`Link`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/Film.js
> +              <a href="add-review.html" className="btn movie-card__button">Add review</a>
`Link`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/Film.js
> +              <a href="add-review.html" className="btn movie-card__button">Add review</a>
и ниже тоже

2020-10-21 13:23 UTC, aelyseev commented on src/pages/Main.js
> +};
или `isRequired` или `defaultProps`

2020-10-21 13:23 UTC, aelyseev commented on src/pages/MyList.js
> +          <a href="main.html" className="logo__link">
`Link` и ниже тоже

2020-10-21 13:23 UTC, aelyseev commented on webpack.config.js
> +    port: 80,
не ошибка

такой порт требует `sudo`, могут быть проблемы, если на проекте не только вы.

2020-10-21 21:06 UTC, dermorgenstern commented on webpack.config.js
> +    port: 80,
да, это я для dev машины сделал. сделаю назад.

2020-10-22 10:19 UTC, aelyseev commented
> сделать как в видео уроке перерисовку по изменении url не удалось - пытается грузить несуществующую страницу. на stack overflow говорят надо сервер настараивать чтобы выдавал одну и туже страницу.

Верно говорят. Не знаю честно говоря как это на netlify сделать — точнее знаю что но не знаю как именно

2020-10-22 16:17 UTC, dermorgenstern commented
Алексей,
переделал проект, сделал push, по правде говоря в задании писали что внутри
проекта переделывать пока не надо.

С netlify как-то сложно, я думаю надо надо просто сервер сделать и все,
например хероку, там nginx есть.

Евгений.

On Thu, 22 Oct 2020 at 06:20, aelyseev <notifications@github.com> wrote:

> сделать как в видео уроке перерисовку по изменении url не удалось -
> пытается грузить несуществующую страницу. на stack overflow говорят надо
> сервер настараивать чтобы выдавал одну и туже страницу.
>
> Верно говорят. Не знаю честно говоря как это на netlify сделать — точнее
> знаю что но не знаю как именно
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-react/832117-what-to-watch-5/pull/6#issuecomment-714392520>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIKUBDUHUSHS6EG34JNSQHDSMABN7ANCNFSM4SZFZBKQ>
> .
>

2020-10-22 18:20 UTC, aelyseev commented on src/pages/AddReview.js
> +            <Link to={`/`} title="main page" className="logo__link">
когда строкового значение можно просто `<Link to="/"`

2020-10-22 18:25 UTC, aelyseev commented
> по правде говоря в задании писали что внутри
проекта переделывать пока не надо.

Там написано что не обязательно — так что вы молодец, что сделали. И если вы считаете какие-то мои замечания чрезмерными — говорите об этом.

2020-10-22 18:25 UTC, aelyseev approved these changes

2020-10-22 18:25 UTC, merged